# End map. Small bounds: the End is mostly void and there is little to show
# beyond the main island unless you have built out there.

world: "world"
dimension: "minecraft:the_end"
name: "The End"
sorting: 2

min-x: -1024
max-x: 1024
min-z: -1024
max-z: 1024

render-caves: false
ambient-light: 0.6
storage: "file"
