import fs from 'node:fs';

const audit = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
const idx = JSON.parse(fs.readFileSync(process.argv[3], 'utf8'));

// Mods we drop regardless of Modrinth metadata, because they are client-only in
// practice or actively harmful on a dedicated server.
// NOTE: e4mc is deliberately NOT here. It is server_side:required on Modrinth
// and its ServerConnectionListener mixin fires on a dedicated server's TCP
// listener, which is exactly how this server is exposed to the internet.
const FORCE_DROP = new Set([
  'do-a-barrel-roll',// pure client movement/camera
  'xaeros-minimap',  // client UI (server companion is a separate mod)
  'xaeros-world-map',// client UI
  'distanthorizons', // client LOD renderer; server module is opt-in and heavy
]);

const keep = [];
const dropped = [];

for (const r of audit.rows) {
  const reason =
    r.server === 'unsupported' ? 'server_side=unsupported'
    : FORCE_DROP.has(r.slug) ? 'client-only (manual)'
    : null;
  if (reason) { dropped.push({ slug: r.slug, title: r.title, reason }); continue; }
  keep.push({
    slug: r.slug,
    title: r.title,
    path: r.path,
    url: r.url,
    size: r.size,
    sha512: Object.entries(idxSha(r.path)).length ? idxSha(r.path).sha512 : undefined,
    server: r.server,
  });
}

function idxSha(path) {
  const f = idx.files.find((x) => x.path === path);
  return f?.hashes ?? {};
}

keep.sort((a, b) => a.slug.localeCompare(b.slug));
dropped.sort((a, b) => a.slug.localeCompare(b.slug));

const lock = {
  _comment:
    'Generated by tools/regen-lock.mjs from the .mrpack. Do not hand-edit; rerun the tool when the modpack changes.',
  minecraft: idx.dependencies.minecraft,
  neoforge: idx.dependencies.neoforge,
  packName: idx.name,
  packVersion: idx.versionId,
  generatedFrom: `${idx.name} ${idx.versionId}`,
  counts: { total: idx.files.length, keep: keep.length, dropped: dropped.length },
  mods: keep,
  dropped,
};

fs.writeFileSync(process.argv[4], JSON.stringify(lock, null, 2) + '\n');
console.log(`keep=${keep.length} dropped=${dropped.length} total=${idx.files.length}`);
console.log('total download MB:', (keep.reduce((a, m) => a + m.size, 0) / 1048576).toFixed(1));
